BEGIN;
WITH INVOICES AS (
    SELECT *
    FROM D_POST_INSTALL.T_FILINGS_INVOICE_DETAILS AS I
    WHERE I.FILE_NAME ILIKE '%297%'
)

   , BATCHES AS (
    SELECT *
    FROM D_POST_INSTALL.T_FILING_BATCH_UPLOAD_FILES AS B
)

   , MAIN AS (
    SELECT I.AR_NUMBER
         , I.FEE
         , I.FILE_NAME
         , I.BATCH_ID
         , B.SERVICE_NAME
         , B.WEEK_BATCH
         , B.BATCH_TYPE
    FROM INVOICES AS I
             LEFT JOIN BATCHES AS B
                       ON B.SERVICE_NAME = I.AR_NUMBER
--                            AND B.WEEK_BATCH = I.BATCH_ID
)

SELECT *
FROM MAIN
WHERE WEEK_BATCH IS NULL
;

SELECT *
FROM D_POST_INSTALL.T_FILING_BATCH_UPLOAD_FILES AS B
WHERE B.WEEK_BATCH ILIKE '%331%'
;

-- DELETE
-- FROM D_POST_INSTALL.T_FILING_BATCH_UPLOAD_FILES AS B
-- WHERE B.WEEK_BATCH = '331'
-- ;

SELECT *
FROM D_POST_INSTALL.T_FILINGS_INVOICE_DETAILS AS I
WHERE FILE_NAME ILIKE '%297%'
;

-- DELETE
-- FROM D_POST_INSTALL.T_FILINGS_INVOICE_DETAILS AS I
-- WHERE I.FILE_NAME ILIKE '%297%'
-- ;

COMMIT;
ROLLBACK;